apps/activitylog/urls.py
from django.urls import path
from apps.activitylog import views

app_name = 'activitylog'


urlpatterns = [
    path('list/', views.ActivityLogListView.as_view(), name='activity_log_list'),
    path('data/<int:pk>/', views.ActivityLogDetailsView.as_view(), name='activity_log_data'),
]

apps/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('apps.auth.urls',  namespace='auth')),
    path('', include('apps.dashboards.urls', namespace='dashboards')),
    path('admins/', include('apps.admin.urls', namespace='admins')),





    ## Error 404 and 500 responses
    path("error-404/", TemplateView.as_view(template_name="error/404.html"), name="error_404"),
    path("error-500/", TemplateView.as_view(template_name="error/500.html"), name="error_500"),

]

apps/activitylog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

User = get_user_model()


class ActivityLog(models.Model):
    class ActionTypes(models.TextChoices):
        CREATE = 'Create', 'create'
        READ   = 'Read'  , 'read'
        UPDATE = 'Update', 'update'
        DELETE = 'Delete', 'delete'
        LOGIN  = 'Login' , 'login'
        LOGOUT = 'Logout', 'logout'
        LOGIN_FAILED = 'Login Failed', 'login failed'

    class ActionStatus(models.TextChoices):
        SUCCESS = 'Success', 'success'
        FAILED  = 'Failed' , 'failed'

    actor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    action_type = models.CharField(choices=ActionTypes, max_length=15)
    action_time = models.DateTimeField(auto_now_add=True)

    remarks = models.TextField(null=True, blank=True)
    status  = models.CharField(choices=ActionStatus, max_length=7, default=ActionStatus.SUCCESS)
    data    = models.JSONField(default=dict)

    # object_id = models.PositiveIntegerField(blank=True, null=True)
    object_id = models.CharField(max_length=50, blank=True, null=True)

    # for generic relations
    content_type = models.ForeignKey(
        ContentType, models.SET_NULL, blank=True, null=True
    )
    content_object = GenericForeignKey()

    def __str__(self) -> str:
        return f"{self.action_type} by {self.actor} on {self.action_time}"

apps/activitylog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from django.contrib.auth import get_user_model
User = get_user_model()

from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.sessions.models import Session
from django.contrib import messages

from django.utils.decorators import method_decorator
from django.utils import timezone

from django.db.models import Q, Count, F
from django.db.models.functions import ExtractMonth, ExtractYear

from django.http import HttpRequest, HttpResponse, JsonResponse, Http404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage
from django.core.exceptions import ValidationError, PermissionDenied

from datetime import datetime, timedelta
from random import randint

from django.views import View
from django.views import generic
import json

## Custom 
from config.permission import is_superuser_or_staff, is_superadmin
from apps.core.utils2 import CustomPaginator, ExcelDataDownload
from apps.activitylog.models import ActivityLog

"""
    ActivityLog List
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')
class ActivityLogListView(View, LoginRequiredMixin):
    template_name = "activitylog/list.html"
    obj_per_page = 10

    def get_queryset(self):
        queryset = ActivityLog.objects.all().order_by('-action_time')
        return queryset


    def get(self, request, *args, **kwargs):
        queryset = self.get_queryset()

        ## NOTE:- Filter values from the GET parameters
        # user_type   = request.GET.get('user_type', '')
        # is_verified = request.GET.get('is_verified', '')
        # is_active   = request.GET.get('is_active', '')
        # created_at  = request.GET.get('created_at', '')

        # # print("----------------------")
        # # print("user_type   = ", user_type)
        # # print("is_verified = ", is_verified)
        # # print("is_active   = ", is_active)
        # # print("created_at  = ", created_at)
        # # print("----------------------")

        # if user_type:
        #     users = users.filter(user_type=user_type)
        # if is_verified != '':
        #     users = users.filter(is_verified=bool(int(is_verified)))
        # if is_active != '':
        #     users = users.filter(is_active=bool(int(is_active)))

        # if created_at != '':
        #     if 'to' in created_at:
        #         from_date_str, to_date_str = created_at.split(" to ")
        #         from_date = datetime.strptime(from_date_str, "%d/%m/%y")
        #         to_date   = datetime.strptime(to_date_str, "%d/%m/%y")

        #         users = users.filter(created_at__range=[from_date, to_date])
        #     else:
        #         try:
        #             specific_date = datetime.strptime(created_at, '%d/%m/%y') 
        #             users = users.filter(created_at__date=specific_date) # Handle specific date
        #         except ValueError:
        #             pass # Handle invalid date format

        
        ## NOTE:- For Pagination
        custom_paginator = CustomPaginator(queryset, self.obj_per_page)
        paginated_data = custom_paginator.get_paginated_data(request)

        context = {
            'activitys': paginated_data['page_obj'],
            'page_obj': paginated_data['page_obj'],
            'page_range': paginated_data['page_range'],
            'queryset_count': queryset.count(),
        }

        return render(request, self.template_name, context)
    




"""
    ActivityLog Details
"""
@method_decorator(user_passes_test(is_superuser_or_staff, 
    login_url=reverse_lazy('auth:login')), name='dispatch')

class ActivityLogDetailsView(generic.DetailView, LoginRequiredMixin):
    model = ActivityLog
    template_name = "activitylog/data_view.html"
    context_object_name = "log_datas"

    def get_object(self, queryset=None):
        return get_object_or_404(ActivityLog.objects.all(), pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        log_data = context['object']
        
        print("-----------------")
        print("Data =", log_data.data)
        print("-----------------")

        context['log_datas'] = log_data.data
        context['action_type'] = log_data.action_type
        return context

    

# class ActivityLogDetailsView(generic.DetailView, LoginRequiredMixin):
#     model = ActivityLog
#     template_name = "activitylog/data_view2.html"
#     context_object_name = "log_datas"

#     def get_object(self, queryset=None):
#         return get_object_or_404(ActivityLog.objects.all(), pk=self.kwargs['pk'])

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)

#         log_data = context['object']
#         log_data.data = json.loads(log_data.data)  # Parse JSON string into dictionary

#         ## Oly Field Data
#         # fields_data = [item['fields'] for item in log_data.data]
        
#         print("-----------------")
#         print("Data =", log_data.data)
#         # print("Data =", fields_data)
#         # for item in log_data.data:
#             # print("Fields = ", item['fields'])
#             # print("Fields = ", item['fields']['email'])
#         print("-----------------")

#         # context['log_datas'] = [log_data]
#         context['log_datas'] = log_data.data
#         context['action_type'] = log_data.action_type
#         return context

        

    
# class ActivityLogDetailsView(generic.DetailView, LoginRequiredMixin):
#     model = ActivityLog
#     template_name = "activitylog/data_view.html"
#     context_object_name = "log_datas"

#     def get_context_data(self, *args, **kwargs):
#         data = super().get_context_data(**kwargs)
#         data['log_datas'] = self.model.objects.get(id=self.kwargs['pk'])
#         return data

apps/activitylog/templates/activitylog/data_view.html
{% extends 'layouts/master.html' %}
{% load math %}


{% load static %}
{% load humanize %}

{% block title %}
    Company | List
{% endblock title %}



{% block styles %}

<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- For TIme Modiul -->
<link href="{% static 'vendors/flatpickr/flatpickr.min.css' %}" rel="stylesheet" />
{% endblock styles %}




{% block content %}
<div class="col-md-8 card mb-3">

    <!-- Header Content -->
    <div class="card-header bg-light">
        <div class="row flex-between-center">

            <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">
                    <i class="fa-solid fa-hourglass-half fs-1 me-2"></i>
                    Activity Log Data
                </h5>
            </div>

            <div class="col-8 col-sm-auto ms-auto text-end ps-0">
            </div>
        </div>
    </div>

    <!-- Body Content -->
    <div class="card-body p-4">
        <div class="table-responsive">

            <div class="d-flex justify-content-between mb-3">

            </div>

            <table width="100%" class="table table-bordered table-striped table-hover fs--1 mb-0">
                <h6 class="fw-semi-bold ls mb-3 text-uppercase">Log Data</h6>
                <thead style="background: rgb(141, 134, 134); color: white;">
                    <tr>
                        <th class="col-4">Field</th>
                        <th class="col-8">Value</th>
                    </tr>
                </thead>
                <tbody>
                    {% for field_key, field_value in log_datas.fields.items %}
                        <tr>
                            <td class="fw-semi-bold" style="text-transform: capitalize;">
                                {{ field_key|format_key }}
                            </td>
                            <td>{{ field_value }}</td>
                        </tr>
                    {% endfor %}

                    <!-- Assuming 'company' is a field in log_data -->
                    {% if action_type == 'Create' or action_type == 'Update' %}
                    <tr>
                        <td class="fw-semi-bold">Details</td>
                        <td>
                            {% if log_datas.model == 'users.user' %}
                                <a class="btn btn-primary btn-sm"
                                    href="{% url 'employee:employee_details' log_datas.pk %}">
                                    View Employee Details
                                </a>
                            {% elif log_datas.model == 'product.company' %}
                                <a class="btn btn-primary btn-sm"
                                    href="{% url 'product:company_details' log_datas.pk %}">
                                    View Company Details
                                </a>
                            {% elif log_datas.model == 'product.order' %}
                                <a class="btn btn-primary btn-sm"
                                    href="{% url 'product:order_details' log_datas.pk %}">
                                    View Order Details
                                </a>
                            {% elif log_datas.model == 'product.transaction' %}
                                <a class="btn btn-primary btn-sm"
                                    href="">
                                    View Order Details
                                </a>
                            {% else %}
                                No Details Available
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                </tbody>            
            </table>
        </div>

        <!-- New table for displaying changes -->
        {% if log_datas.changes.items %}
            <div class="table-responsive mt-4">
                <table width="100%" class="table table-bordered table-striped table-hover fs--1 mb-0">
                    <h6 class="fw-semi-bold ls mb-3 text-uppercase">Changes</h6>
                    <thead style="background: rgb(141, 134, 134); color: white;">
                        <tr>
                            <th class="col-4">Field</th>
                            <th class="col-4">Old Value</th>
                            <th class="col-4">New Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for field_name, change_data in log_datas.changes.items %}
                            <tr>
                                <td style="text-transform: capitalize;">{{ field_name }}</td>
                                <td>{{ change_data.old }}</td>
                                <td>{{ change_data.new }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>            
                </table>
            </div>
        {% endif %}
    </div>

</div>

{% endblock content %}

apps/activitylog/templates/activitylog/data_view2.html
{% extends 'layouts/master.html' %}

{% load static %}
{% load humanize %}

{% block title %}
    Company | List
{% endblock title %}



{% block styles %}

<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- For TIme Modiul -->
<link href="{% static 'vendors/flatpickr/flatpickr.min.css' %}" rel="stylesheet" />
{% endblock styles %}




{% block content %}
<div class="col-md-8 card mb-3">

    <!-- Header Content -->
    <div class="card-header bg-light">
        <div class="row flex-between-center">

            <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">
                    <i class="fa-solid fa-hourglass-half fs-1 me-2"></i>
                    Activity Log Data
                </h5>
            </div>

            <div class="col-8 col-sm-auto ms-auto text-end ps-0">
                <!-- <a class="btn btn-primary btn-sm" 
                    href="{% if log_datas.model.product.company %}{% url 'product:company_details' log_datas.pk %}{% endif %}">
                    View
                </a> -->
            </div>
        </div>
    </div>

    <!-- Body Content -->
    <div class="card-body p-4">
        <div class="table-responsive">

            <div class="d-flex justify-content-between mb-3">

            </div>

            <table width="100%" class="table table-bordered table-striped table-hover fs--1 mb-0">
                <h6 class="fw-semi-bold ls mb-3 text-uppercase">Log Data</h6>
                <thead style="background: rgb(141, 134, 134); color: white;">
                    <tr>
                        <th class="col-4">Attribute</th>
                        <th class="col-8">Value</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log_data in log_datas %}
                        {% for field_key, field_value in log_data.fields.items %}
                            <tr>
                                <td class="fw-semi-bold">{{ field_key }}</td>
                                <td>{{ field_value }}</td>
                            </tr>
                        {% endfor %}
                        <!-- Assuming 'company' is a field in log_data -->
                        
                        {% if action_type == 'Create' or action_type == 'Update' %}
                        <tr>
                            <td class="fw-semi-bold">Details</td>
                            <td>
                                {% if log_data.model == 'users.user' %}
                                    <a class="btn btn-primary btn-sm"
                                        href="{% url 'employee:employee_details' log_data.pk %}">
                                        View Employee Details
                                    </a>
                                {% elif log_data.model == 'product.company' %}
                                    <a class="btn btn-primary btn-sm"
                                        href="{% url 'product:company_details' log_data.pk %}">
                                        View Company Details
                                    </a>
                                {% else %}
                                    No Details Available
                                {% endif %}
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>


                <!-- <tbody>
                    {% for log_data in log_datas %}
                        {% for key, value in log_data.items %}
                            <tr>
                                <td class="fw-semi-bold">{{ key }}</td>
                                <td>{{ value }}</td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody> -->
                

                <!-- <tbody>
                    {% for log_data in log_datas %}
                        {% for data in log_data.data %}
                            <tr>
                                <td class="fw-semi-bold">
                                    Model
                                </td>
                                <td>
                                    {{ data.model }}
                                </td>
                            </tr>
                            <tr>
                                <td class="fw-semi-bold">
                                    ID
                                </td>
                                <td>
                                    {{ data.pk }}
                                </td>
                            </tr>
                            <tr>
                                <td class="fw-semi-bold">
                                    Fields
                                </td>
                                <td>
                                    <ul>
                                        {% for key, value in data.fields.items %}
                                            <li><strong>{{ key }}:</strong> {{ value }}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody> -->
                

            </table>
        </div>
    </div>

</div>

{% endblock content %}

apps/activitylog/templates/activitylog/data_view3.html
{% extends 'layouts/master.html' %}

{% load static %}
{% load humanize %}

{% block title %}
    Company | List
{% endblock title %}



{% block styles %}

<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- For TIme Modiul -->
<link href="{% static 'vendors/flatpickr/flatpickr.min.css' %}" rel="stylesheet" />
{% endblock styles %}




{% block content %}
<div class="col-md-8 card mb-3">

    <!-- Header Content -->
    <div class="card-header bg-light">
        <div class="row flex-between-center">

            <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">
                    <i class="fa-solid fa-hourglass-half fs-1 me-2"></i>
                    Activity Log Data
                </h5>
            </div>

            <div class="col-8 col-sm-auto ms-auto text-end ps-0">
                <!-- <a class="btn btn-primary btn-sm" 
                    href="{% if log_datas.model.product.company %}{% url 'product:company_details' log_datas.pk %}{% endif %}">
                    View
                </a> -->
            </div>
        </div>
    </div>

    <!-- Body Content -->
    <div class="card-body p-4">
        <div class="table-responsive">

            <div class="d-flex justify-content-between mb-3">

            </div>

            <table width="100%" class="table table-bordered table-striped table-hover fs--1 mb-0">
                <h6 class="fw-semi-bold ls mb-3 text-uppercase">Log Data</h6>
                <thead style="background: rgb(141, 134, 134); color: white;">
                    <tr>
                        <th class="col-4">Attribute</th>
                        <th class="col-8">Value</th>
                    </tr>
                </thead>
                <tbody>
                    {% for field_key, field_value in log_datas.fields.items %}
                        <tr>
                            <td class="fw-semi-bold">{{ field_key }}</td>
                            <td>{{ field_value }}</td>
                        </tr>
                    {% endfor %}
                    <!-- Assuming 'company' is a field in log_data -->
                    {% if action_type == 'Create' or action_type == 'Update' %}
                    <tr>
                        <td class="fw-semi-bold">Details</td>
                        <td>
                            {% if log_datas.model == 'users.user' %}
                                <a class="btn btn-primary btn-sm"
                                    href="{% url 'employee:employee_details' log_datas.pk %}">
                                    View Employee Details
                                </a>
                            {% elif log_datas.model == 'product.company' %}
                                <a class="btn btn-primary btn-sm"
                                    href="{% url 'product:company_details' log_datas.pk %}">
                                    View Company Details
                                </a>
                            {% else %}
                                No Details Available
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                </tbody>            
            </table>
            
        </div>
    </div>

</div>

{% endblock content %}

apps/activitylog/templates/activitylog/list.html
{% extends 'layouts/master.html' %}

{% load static %}
{% load humanize %}

{% block title %}
    Company | List
{% endblock title %}



{% block styles %}

<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- For TIme Modiul -->
<link href="{% static 'vendors/flatpickr/flatpickr.min.css' %}" rel="stylesheet" />
{% endblock styles %}




{% block content %}
<div class="card mb-3">

    <!-- Header Content -->
    <div class="card-header bg-light">
        <div class="row flex-between-center">

            <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">
                    <i class="fa-solid fa-hourglass-half fs-1 me-2"></i>
                    Activity Log List
                </h5>
            </div>

            <div class="col-8 col-sm-auto ms-auto text-end ps-0">
                <div class="d-flex flex-row" id="orders-actions">
                    <!-- <button class="btn btn-konnect-default btn-sm mx-2" type="button" 
                        data-bs-toggle="modal" data-bs-target="#filter-modal">
                        <span class="fas fa-filter"></span>
                        <span class="d-none d-sm-inline-block ms-1">Filter</span>
                    </button> -->
                </div>
            </div>
        </div>
    </div>

    <!-- Body Content -->
    <div class="card-body p-4">
        <div class="table-responsive">

            <div class="d-flex justify-content-between mb-3">

            </div>

            <table width="100%" class="table table-bordered table-striped table-hover fs--1 mb-0">
                <thead class="bg-200 text-900">
                    <tr>
                        <th class="">S/N</th>
                        <th>User</th>
                        <th class="text-center">Activity Type</th>
                        <th>Remarks</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Time</th>
                        <th class="text-center">View Data</th>
                    </tr>
                </thead>
                <tbody id="bulk-select-body">
                    {% if page_obj %}
                        {% for log in page_obj %}
                        <tr>
                            <td>
                                {{ page_obj.start_index|add:forloop.counter0 }}
                            </td>

                            <td>
                                <span class="badge badge-soft-dark fs--1">{{log.actor.name}}</span><br>
                                <span class="badge bg-light text-dark fs--1">{{log.actor.phone}}</span>

                            </td>


                            <td class="text-center">
                                <span class="badge badge-soft-{% if log.action_type == 'Create' %}success{% elif log.action_type == 'Update' %}warning{% elif log.action_type == 'Delete' %}danger{% endif %} fs--1">
                                {{ log.action_type }}
                                </span>
                            </td>

                            <td>
                                <span class="badge bg-light text-dark fs--1">{{log.remarks}}</span>
                            </td>

                            <td class="text-center">
                                <span class="badge badge-soft-{% if log.status == 'Success' %}success{% else %}danger{% endif %} fs--1">{{log.status}}</span>
                            </td>

                            <td class="text-center">
                                <span class="badge badge-soft-light fs--2">
                                    {{ log.action_time|date:"D, d/M/Y" }}
                                </span><br>
                                <span class="badge badge-soft-light fs--2">
                                    {{ log.action_time|date:"g:i A" }}
                                </span>
                            </td>

                            <td class="text-center">
                                <a class="text-primary" href="{% url 'activitylog:activity_log_data' log.id %}">
                                    <span class="fas fa-eye text-primary"></span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="7" class="text-center fs-2 fw-bold">
                                Activity Log Data Not Found!
                            </td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Pagination snd Counting -->
    {% include 'common/pagination.html' %}

</div>


<!-- Filter Modal -->
{% include 'employee/filter.html' %}


{% endblock content %}




{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
{% endblock js %}